In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset.csv",header = None, names=['Hour','Immobilized_bus','Broken_Truck','Vehicle_excess','Accident_victim','Running_over','Fire_vehicles','Occurrence_involving_freight','Incident_involving_dangerous_freight','Lack_of_electricity','Fire','Point_of_flooding','Manifestations','Defect_in_the_network_of_trolleybuses','Tree_on_the_road','Semaphore_off','Intermittent_Semaphore','Slowness_in_traffic_percent'])
data

      Hour  ...  Slowness_in_traffic_percent
0    07:00  ...                          4.1
1    07:30  ...                          6.6
2    08:00  ...                          8.7
3    08:30  ...                          9.2
4    09:00  ...                         11.1
..     ...  ...                          ...
130  18:00  ...                         17.8
131  18:30  ...                         18.1
132  19:00  ...                         17.7
133  19:30  ...                         17.4
134  20:00  ...                         12.1

[135 rows x 18 columns]

In [4]:
data['Hour'].replace(["07:00","07:30","08:00","08:30","09:00","09:30","10:00","10:30","11:00"],'Morning',inplace=True)
data['Hour'].replace(["11:30","12:00","12:30","13:00","13:30","14:00","14:30","15:00","15:30","16:00","16:30"],'Afternoon',inplace=True)
data['Hour'].replace(["17:00","17:30","18:00","18:30","19:00","19:30"],'evening',inplace=True)
data['Hour'].replace(["20:00","20:30"],'night',inplace=True)

In [5]:
X = pd.get_dummies(data,columns=["Hour"],drop_first=True)
X

     Immobilized_bus  Broken_Truck  ...  Hour_evening  Hour_night
0                  0             0  ...             0           0
1                  0             0  ...             0           0
2                  0             0  ...             0           0
3                  0             0  ...             0           0
4                  0             0  ...             0           0
..               ...           ...  ...           ...         ...
130                1             0  ...             1           0
131                0             0  ...             1           0
132                1             0  ...             1           0
133                0             4  ...             1           0
134                0             0  ...             0           1

[135 rows x 20 columns]

In [6]:
y = data[['Slowness_in_traffic_percent']]
y

     Slowness_in_traffic_percent
0                            4.1
1                            6.6
2                            8.7
3                            9.2
4                           11.1
..                           ...
130                         17.8
131                         18.1
132                         17.7
133                         17.4
134                         12.1

[135 rows x 1 columns]

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1,shuffle=False)

In [8]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [9]:
y_pred = model.predict(X)

In [10]:
poly = PolynomialFeatures()
poly.fit_transform(X)

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 1., 0., 0.],
       [1., 0., 4., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [11]:
mse = mean_squared_error(y,y_pred)
print(f"\nMSE: {mse}")

MSE: 8.735904098558612e-31

In [12]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y, y_pred)

2.7632217501781674e-16

In [13]:
from sklearn.metrics import r2_score
r2_score(y, y_pred)

1.0